steps:
  - name: maven:3-openjdk-21
    entrypoint: mvn
    args: ["clean", "package", "-Dimage=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/dataflow:${_VERSION}"]
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
    args: ["gcloud", "dataflow", "flex-template", "build",
           "gs://${_BUCKET}/${_VERSION}",
           "--image", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/dataflow:${_VERSION}",
           "--sdk-language", "JAVA"]
  - name: maven:3-openjdk-21
    entrypoint: mvn
    args: ["clean", "package", "-DskipTests", "-Pdirect", "-Dimage=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/direct:${_VERSION}"]
  - name: maven:3-openjdk-21
    entrypoint: mvn
    args: ["clean", "package", "-DskipTests", "-Pserver", "-Dimage=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/server:${_VERSION}"]
  - name: maven:3-openjdk-21
    entrypoint: mvn
    args: ["clean", "package", "-DskipTests", "-Pportable", "-Dimage=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/portable:${_VERSION}"]
substitutions:
  _BUCKET: "{SET YOUR BUCKET}"
  _REGION: "{SET YOUR GAR REPOSITORY REGION}"
  _REPOSITORY: "{SET YOUR GAR REPOSITORY NAME}"
  _VERSION: ${BRANCH_NAME}
options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY